export const IPC = {
  ping: 'ping',
  configLoad: 'config:load',
  configSave: 'config:save',
  scanFolder: 'scan:folder',
  zaloOpen: 'zalo:open',
  zaloLoginStatus: 'zalo:login-status',
  zaloWaitLogin: 'zalo:wait-login',
  zaloLogin: 'zalo:login',
  zaloLogout: 'zalo:logout',
  zaloSearch: 'zalo:search',
  zaloPickCandidate: 'zalo:pick-candidate',
  zaloPickCandidateResponse: 'zalo:pick-candidate-response',
  zaloConfirmSend: 'zalo:confirm-send',
  zaloConfirmSendResponse: 'zalo:confirm-send-response',
  runStart: 'run:start',
  runStop: 'run:stop',
  runProgress: 'run:progress',
  runLog: 'run:log',
  runDone: 'run:done',
  updaterCheck: 'updater:check',
  updaterQuitAndInstall: 'updater:quit-and-install',
  updaterEvent: 'updater:event',
  debugDump: 'debug:dump',
  debugGetLog: 'debug:getLog',
  debugGetLogPath: 'debug:getLogPath',
  debugClearLog: 'debug:clearLog',
  readImage: 'read:image',
  pickFolder: 'pick:folder',
  selectorsGet: 'selectors:get',
  selectorsGetPath: 'selectors:getPath',
  selectorsReload: 'selectors:reload',
  getVersion: 'get:version'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
